name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macos-13 = x86_64, macos-14 = arm64
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install build dependencies
        shell: pwsh
        if: matrix.os == 'windows-latest'
        run: |
          curl -O https://litesync.io/download/litesync-free-windows-x86_64.tar.gz
          tar -xzvf litesync-free-windows-x86_64.tar.gz
          .\install.bat

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0

      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v3
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: wheelhouse
